// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tiwifcyaqswborvdwvmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpd2lmY3lhcXN3Ym9ydmR3dm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODE2NDksImV4cCI6MjA2OTg1NzY0OX0.BHPWc8lw3y9Tnb4ymM3K0AtE2YLkH3bk0_raqbq1c58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});